In [1]:
daily_kwh=[400,850,300,500,500,600]
total_energy=sum(daily_kwh)
print("Total Enerey Used: ",total_energy)

Total Enerey Used:  3150

In [2]:
building_usage={
    "cse":400,
   "hostel": 850
  }
print("Hostel Used",building_usage['hostel'],"kwh")

Hostel Used 850 kwh

In [10]:
# Creating 'Book1.csv' with the specified structure and data
csv_data = """Date,Building,KWH_Used,Peak_Hour_Used
05-10-2026,CSE,400,120
06-10-2026,HOSTEL,850,250
07-10-2026,ADMIN,300,110
08-10-2026,ECE,500,325
09-10-2026,CIVIL,500,210
10-10-2026,HOSTEL,600,111"""

with open("Book1.csv", "w") as file:
    file.write(csv_data)

def calculate_bill(kwh, rate_per_unit):
    return kwh * rate_per_unit
todays_bill = calculate_bill(600, 8)
print("Today's estimated bill is Rs.", todays_bill)
print("'Book1.csv' has been successfully created with your requested data structure!")

Today's estimated bill is Rs. 4800
'Book1.csv' has been successfully created with your requested data structure!

In [11]:
with open("Book1.csv","r") as file:
  for line in file.readlines():
    print(line.strip())

Date,Building,KWH_Used,Peak_Hour_Used
05-10-2026,CSE,400,120
06-10-2026,HOSTEL,850,250
07-10-2026,ADMIN,300,110
08-10-2026,ECE,500,325
09-10-2026,CIVIL,500,210
10-10-2026,HOSTEL,600,111

In [12]:
# import the pandas library
import pandas as pd

# load the dataset you created
df = pd.read_csv("Book1.csv")

# display the first few rows of the data
print("Here is the raw data:")
display(df.head())

# Group the data to see total usage per building
building_totals = df.groupby("Building")["KWH_Used"].sum()

print("\nTotal usage per building:")
print(building_totals)

# Generate a statistical summary (average, min, max) of the numeric columns
print("\nStatistical Summary:")
display(df.describe())

Here is the raw data:

         Date Building  KWH_Used  Peak_Hour_Used
0  05-10-2026      CSE       400             120
1  06-10-2026   HOSTEL       850             250
2  07-10-2026    ADMIN       300             110
3  08-10-2026      ECE       500             325
4  09-10-2026    CIVIL       500             210

Total usage per building:
Building
ADMIN      300
CIVIL      500
CSE        400
ECE        500
HOSTEL    1450
Name: KWH_Used, dtype: int64

Statistical Summary:

         KWH_Used  Peak_Hour_Used
count    6.000000        6.000000
mean   525.000000      187.666667
std    189.076704       89.144078
min    300.000000      110.000000
25%    425.000000      113.250000
50%    500.000000      165.000000
75%    575.000000      240.000000
max    850.000000      325.000000

In [15]:
with open("README.md", "w") as file:
    file.write("#smart campus energy project\n")
    file.write("This repository contains my week one hands on python and pandas assignments.\n")
    file.write("Created by:srikar gurajapu ")
print("README.md has been created successfully")

README.md has been created successfully